export const ACTIONS = {
  //GET_MEMBER_REQUEST
  //ADD_MEMBER_REQUEST
  //DELETE_MEMBER_REQUEST
  API_CALL_REQUEST: 'API_CALL_REQUEST',
  API_CALL_SUCCESS: 'API_CALL_SUCCESS',
  API_CALL_FAILURE: 'API_CALL_FAILURE',
  API_ADD_REQUEST: 'API_ADD_REQUEST',
  API_ADD_SUCCESS: 'API_ADD_SUCCESS',
  API_ADD_FAILURE: 'API_ADD_FAILURE',
  API_DELETE_REQUEST: 'API_DELETE_REQUEST',
  API_DELETE_SUCCESS: 'API_DELETE_SUCCESS',
  API_DELETE_FAILURE: 'API_DELETE_FAILURE',
  API_UPDATE_REQUEST: 'API_UPDATE_REQUEST',
  API_UPDATE_SUCCESS: 'API_UPDATE_SUCCESS',
  API_UPDATE_FAILURE: 'API_UPDATE_FAILURE',
};
