export const ACTIONS = {
  //GET_MEMBER_REQUEST
  //ADD_MEMBER_REQUEST
  //DELETE_MEMBER_REQUEST
  MEMBER_REQUEST: 'MEMBER_REQUEST',
  MEMBER_REQUEST_SUCCESS: 'MEMBER_REQUEST_SUCCESS',
  MEMBER_REQUEST_FAILURE: 'MEMBER_REQUEST_FAILURE',
  ADD_MEMBER_REQUEST: 'ADD_MEMBER_REQUEST',
  ADD_MEMBER_SUCCESS: 'ADD_MEMBER_SUCCESS',
  ADD_MEMBER_FAILURE: 'ADD_MEMBER_FAILURE',
  DELETE_MEMBER_REQUEST: 'DELETE_MEMBER_REQUEST',
  DELETE_MEMBER_SUCCESS: 'DELETE_MEMBER_SUCCESS',
  DELETE_MEMBER_FAILURE: 'DELETE_MEMBER_FAILURE',
  UPDATE_MEMBER_REQUEST: 'UPDATE_MEMBER_REQUEST',
  UPDATE_MEMBER_SUCCESS: 'UPDATE_MEMBER_SUCCESS',
  UPDATE_MEMBER_FAILURE: 'UPDATE_MEMBER_FAILURE',
  SEARCH_MEMBER_REQUEST: 'SEARCH_MEMBER_REQUEST',
  SEARCH_MEMBER_SUCCESS: 'SEARCH_MEMBER_SUCCESS',
  SEARCH_MEMBER_FAILURE: 'SEARCH_MEMBER_FAILURE',
};
