export enum ISSUE_ACTIONS {
  ISSUE_GET = 'ISSUE_GET',
  ISSUE_GET_SUCCESS = 'ISSUE_GET_SUCCESS',
  ISSUE_GET_FAILURE = 'ISSUE_GET_FAILURE',
  ADD_ISSUE_REQUEST = 'ADD_ISSUE_REQUEST',
  ADD_ISSUE_SUCCESS = 'ADD_ISSUE_SUCCESS',
  ADD_ISSUE_FAILURE = 'ADD_ISSUE_FAILURE',
  DELETE_ISSUE_REQUEST = 'DELETE_ISSUE_REQUEST',
  DELETE_ISSUE_SUCCESS = 'DELETE_ISSUE_SUCCESS',
  DELETE_ISSUE_FAILURE = 'DELETE_ISSUE_FAILURE',
  UPDATE_ISSUE_REQUEST = 'UPDATE_ISSUE_REQUEST',
  UPDATE_ISSUE_SUCCESS = 'UPDATE_ISSUE_SUCCESS',
  UPDATE_ISSUE_FAILURE = 'UPDATE_ISSUE_FAILURE',
  SEARCH_ISSUE_REQUEST = 'SEARCH_ISSUE_REQUEST',
  SEARCH_ISSUE_SUCCESS = 'SEARCH_ISSUE_SUCCESS',
  SEARCH_ISSUE_FAILURE = 'SEARCH_ISSUE_FAILURE',
}

export enum COMMENT_ACTIONS {
  COMMENT_GET = 'COMMENT_GET',
  COMMENT_GET_SUCCESS = 'COMMENT_GET_SUCCESS',
  COMMENT_GET_FAILURE = 'COMMENT_GET_FAILURE',
  ADD_COMMENT_REQUEST = 'ADD_COMMENT_REQUEST',
  ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS',
  ADD_COMMENT_FAILURE = 'ADD_COMMENT_FAILURE',
  DELETE_COMMENT_REQUEST = 'DELETE_COMMENT_REQUEST',
  DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS',
  DELETE_COMMENT_FAILURE = 'DELETE_COMMENT_FAILURE',
}
